### ISSUE TITLE
Is there a way to disable rewriting a file?

### ISSUE THREAD

**Issue by kumarharsh** [codemod-js/codemod#194] opened 2018-12-26 14:23 UTC
I'm using codemods to do searches across files for complicated things which a regular grep can't fulfill (such as: does any file have a component <XYZ> which has these two particular attributes). When my codemod finds files matching the said properties, I output the list to another file. I don't mutate the AST in any way (these search transforms are just a bunch of `if-else` checks and a `console.error()` to write the filename to another file).

One issue while doing this is that codemod modifies all the files which it touches. It forcefully transforms line endings, adds or removes some braces here and there, etc. Then I have to do a `git checkout -- .` always after running the codemod.

Is there a way to disable the codemod from writing the file it touches? I'd like it to just read the file, run the non-mutating transform and just let the file be.

**Comment by eventualbuddha** [comment] 2018-12-27 01:44
Have you tried it with `--dry-run`?

**Comment by kumarharsh** [comment] 2018-12-27 08:07
That's it! Perfect. I couldn't find anything in the readme for it, but it's there in the cli tool. The flag is called `--dry`. Thanks 👍

**Comment by eventualbuddha** [comment] 2018-12-27 15:21
So you have a codemod which doesn't alter the AST, but the files are still being modified? I've seen things like that and they're typically bugs in [recast](https://github.com/benjamn/recast). Can you provide a couple examples of the unwanted diffs?

**Comment by kumarharsh** [comment] 2018-12-28 08:16
Sure, check out this in ASTExplorer: https://astexplorer.net/#/gist/63a503b3b38c148a06d6438bad35af65/e81a51e13fc87be488af7801bb441351e12f7f91

**Comment by eventualbuddha** [comment] 2019-01-03 23:37
This seems to happen even with something as small as this:

```js
class A {
  a = {};
}
```

which becomes this:

```js
class A {
  a = {};}
```

Something about reprinting class properties is probably broken in recast. I'll take a look later if I get time (cc @benjamn).

**Comment by kumarharsh** [comment] 2019-01-04 09:32
I have had similar problems with recast for quite a long time. There are also issues like the LF -> CRLF conversion which recast can't do much about even if it worked well. 

I was thinking whether it'd be possible to have a flag which doesn't even call recast on the code, so the file won't even be touched.

**Comment by eventualbuddha** [comment] 2022-12-24 14:35
Closing since, though this remains an issue, the cause of it is not in codemod.

**Closed by eventualbuddha** 2022-12-24 14:35 UTC
